version: "3.8"
services:
  nginx:
    container_name: sb-nginx
    image: "nginx:1.25.3-alpine"
    ports:
      - "3080:80"
      - "443:443"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./dev/certificates:/dev/certificates/"
    links:
      - next
      - db
  next:
    volumes:
      - .:/home/app
      - ./docker/next/entrypoint.sh:/usr/local/sbin/entrypoint.sh
      - .git:/home/app
      - ~/.gitconfig:/etc/gitconfig
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: https://dev.saintebernadattemontpellier.cef.fr
      DATABASE_URL: postgresql://sb:sb@localhost:5432/sb?schema=public
  db:
    environment:
      - PGDATA=/var/lib/pg_data
      - POSTGRES_USER=sb
      - POSTGRES_PASSWORD=sb
      - POSTGRES_DB=sb
