import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";

import "./globals.css";
import { Providers } from "../frontend/providers/Providers";

import localFont from "next/font/local";
import { Navbar } from "../frontend/components/navbar/Navbar";
import { Footer } from "../frontend/components/footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

// Font files can be colocated inside of `app`
const bonbonRegular = localFont({
  src: "../../public/fonts/BonbonRegular.woff",
  display: "swap",
  variable: "--font-bonbonregular",
});

const fontRaleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway"
});

export const metadata: Metadata = {
  title: "Paroisse Sainte Bernadette",
  description: "Generated by create next app",
};

const RootLayout: TFCC = ({ children }) => {
  return (
    <html lang="fr" className={`${inter.className} ${bonbonRegular.variable} ${fontRaleway.variable}`}>
      <body suppressHydrationWarning={true} className="bg-[#f7f9fc]">
        <Providers>
          <Navbar />
          {children}
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
