import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Providers } from "../frontend/components/CProviders";

import localFont from "next/font/local";
import { BNavbar } from "../frontend/components/navbar/BNavbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

// Font files can be colocated inside of `app`
const bonbonRegular = localFont({
  src: "../../public/fonts/BonbonRegular.woff",
  display: "swap",
  variable: "--font-bonbonregular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: TFCC = ({ children }) => {
  return (
    <html lang="fr" className={`${inter.className} ${bonbonRegular.variable}`}>
      <body suppressHydrationWarning={true}>
        <Providers>
          <BNavbar />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
